
import React, { useState } from 'react';
import { 
  X, Twitter, Facebook, MessageCircle, Instagram, Download, 
  Share2, ShieldCheck, FileText, Loader2
} from 'lucide-react';
import { UserProfile } from '../types';
import { jsPDF } from 'jspdf';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  profile: UserProfile;
  totals: { calories: number; protein: number; carbs: number; fat: number };
  burned: number;
}

export const ShareModal: React.FC<ShareModalProps> = ({ isOpen, onClose, profile, totals, burned }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  if (!isOpen) return null;

  const shareText = `Operational Sync Complete. Today's Metabolic Status: ${totals.calories} kcal logged, ${burned} kcal burned. Target: ${profile.targetWeight} kg. Fueled by CalGemini AI.`;
  const shareUrl = window.location.origin;

  const handleSocialShare = (platform: 'twitter' | 'facebook' | 'whatsapp') => {
    let url = '';
    const encodedText = encodeURIComponent(shareText);
    const encodedUrl = encodeURIComponent(shareUrl);

    switch (platform) {
      case 'twitter':
        url = `https://twitter.com/intent/tweet?text=${encodedText}&url=${encodedUrl}`;
        break;
      case 'facebook':
        url = `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}&quote=${encodedText}`;
        break;
      case 'whatsapp':
        url = `https://api.whatsapp.com/send?text=${encodedText}%20${encodedUrl}`;
        break;
    }
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const generatePDF = async () => {
    setIsGenerating(true);
    try {
      const doc = new jsPDF();
      const date = new Date().toLocaleDateString();

      // Header
      doc.setFillColor(15, 23, 42); // slate-950
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('CALGEMINI METABOLIC REPORT', 20, 25);
      doc.setFontSize(10);
      doc.text(`DATE: ${date}`, 160, 25);

      // User Bio
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(14);
      doc.text('OPERATIVE PROFILE', 20, 55);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`NAME: ${profile.name}`, 20, 65);
      doc.text(`GOAL: ${profile.goalType.toUpperCase()}`, 20, 72);
      doc.text(`CURRENT WEIGHT: ${profile.weight} kg`, 20, 79);
      doc.text(`TARGET WEIGHT: ${profile.targetWeight} kg`, 20, 86);

      // Today's Stats
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text("TODAY'S METRICS", 20, 105);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`TOTAL CALORIES LOGGED: ${totals.calories} kcal`, 20, 115);
      doc.text(`TOTAL ENERGY EXPENDED: ${burned} kcal`, 20, 122);
      doc.text(`NET METABOLIC BALANCE: ${totals.calories - burned} kcal`, 20, 129);

      // Macros
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text("MACRO-NUTRIENT DISTRIBUTION", 20, 148);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`PROTEIN: ${totals.protein}g / ${profile.dailyMacroTargets.protein}g`, 20, 158);
      doc.text(`CARBS: ${totals.carbs}g / ${profile.dailyMacroTargets.carbs}g`, 20, 165);
      doc.text(`FAT: ${totals.fat}g / ${profile.dailyMacroTargets.fat}g`, 20, 172);

      // Footer
      doc.setDrawColor(226, 232, 240);
      doc.line(20, 260, 190, 260);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text('This report is generated by CalGemini Metabolic AI. Intelligence derived from real-time somatic analysis.', 20, 270);
      doc.setTextColor(16, 185, 129); // emerald-500
      doc.setFont('helvetica', 'bold');
      doc.text('METABOLIC STATUS: OPTIMIZED', 20, 278);

      // Save or Share
      const pdfBlob = doc.output('blob');
      const pdfFile = new File([pdfBlob], `CalGemini_Report_${date.replace(/\//g, '-')}.pdf`, { type: 'application/pdf' });

      if (navigator.share && navigator.canShare({ files: [pdfFile] })) {
        await navigator.share({
          files: [pdfFile],
          title: 'CalGemini Metabolic Report',
          text: 'Sharing my metabolic intelligence report.'
        });
      } else {
        doc.save(`CalGemini_Report_${date.replace(/\//g, '-')}.pdf`);
      }
    } catch (err) {
      console.error("PDF Gen Error:", err);
      alert("Metabolic documentation failed. Ensure system permissions are active.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div 
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-950/90 backdrop-blur-xl animate-in fade-in duration-300"
      onClick={onClose}
    >
      <div 
        className="bg-white rounded-[48px] w-full max-w-lg p-10 shadow-3xl border border-slate-100 relative overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Dynamic Background Elements */}
        <div className="absolute -top-24 -right-24 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -bottom-24 -left-24 w-64 h-64 bg-blue-500/5 rounded-full blur-3xl pointer-events-none" />

        <button 
          onClick={(e) => {
            e.stopPropagation();
            onClose();
          }}
          className="absolute top-8 right-8 p-3 bg-slate-50 rounded-full hover:bg-slate-100 transition-all z-[60] cursor-pointer hover:rotate-90 active:scale-90"
          aria-label="Close Modal"
        >
          <X className="w-5 h-5 text-slate-400"/>
        </button>

        <div className="space-y-10 relative z-10">
          <div className="text-center space-y-3">
            <div className="w-16 h-16 bg-slate-900 rounded-[24px] flex items-center justify-center mx-auto shadow-xl rotate-3 group-hover:rotate-0 transition-transform">
              <Share2 className="w-8 h-8 text-white" />
            </div>
            <h2 className="text-3xl font-black tracking-tightest leading-none">Share Protocol.</h2>
            <p className="text-[10px] font-black uppercase text-slate-400 tracking-[0.4em]">Broadcasting Metabolic Intelligence</p>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <button onClick={() => handleSocialShare('twitter')} className="group flex flex-col items-center gap-3 p-5 bg-slate-50 rounded-[32px] hover:bg-slate-900 hover:text-white transition-all">
              <div className="w-12 h-12 rounded-2xl bg-white shadow-sm flex items-center justify-center group-hover:bg-white/10 transition-colors">
                <Twitter className="w-6 h-6 text-slate-900 group-hover:text-white" />
              </div>
              <span className="text-[8px] font-black uppercase tracking-widest">Twitter</span>
            </button>
            <button onClick={() => handleSocialShare('facebook')} className="group flex flex-col items-center gap-3 p-5 bg-slate-50 rounded-[32px] hover:bg-slate-900 hover:text-white transition-all">
              <div className="w-12 h-12 rounded-2xl bg-white shadow-sm flex items-center justify-center group-hover:bg-white/10 transition-colors">
                <Facebook className="w-6 h-6 text-slate-900 group-hover:text-white" />
              </div>
              <span className="text-[8px] font-black uppercase tracking-widest">Facebook</span>
            </button>
            <button onClick={() => handleSocialShare('whatsapp')} className="group flex flex-col items-center gap-3 p-5 bg-slate-50 rounded-[32px] hover:bg-slate-900 hover:text-white transition-all">
              <div className="w-12 h-12 rounded-2xl bg-white shadow-sm flex items-center justify-center group-hover:bg-white/10 transition-colors">
                <MessageCircle className="w-6 h-6 text-slate-900 group-hover:text-white" />
              </div>
              <span className="text-[8px] font-black uppercase tracking-widest">WhatsApp</span>
            </button>
            <button onClick={() => alert("Open Instagram and share your PDF report from your camera roll!")} className="group flex flex-col items-center gap-3 p-5 bg-slate-50 rounded-[32px] hover:bg-slate-900 hover:text-white transition-all">
              <div className="w-12 h-12 rounded-2xl bg-white shadow-sm flex items-center justify-center group-hover:bg-white/10 transition-colors">
                <Instagram className="w-6 h-6 text-slate-900 group-hover:text-white" />
              </div>
              <span className="text-[8px] font-black uppercase tracking-widest">Instagram</span>
            </button>
          </div>

          <div className="space-y-4">
             <div className="p-6 bg-slate-900 text-white rounded-[32px] shadow-2xl relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none group-hover:rotate-12 transition-transform duration-700"><FileText className="w-24 h-24" /></div>
                <div className="relative z-10 flex flex-col sm:flex-row items-center justify-between gap-6">
                   <div className="space-y-1 text-center sm:text-left">
                     <p className="text-[8px] font-black uppercase opacity-40 tracking-widest">Official Documentation</p>
                     <h4 className="text-xl font-black">Metabolic PDF Report</h4>
                   </div>
                   <button 
                    onClick={generatePDF}
                    disabled={isGenerating}
                    className="px-8 py-4 bg-emerald-500 text-slate-950 rounded-2xl font-black text-[10px] uppercase tracking-widest flex items-center gap-2 hover:scale-105 transition-all shadow-xl disabled:opacity-50"
                   >
                     {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                     {isGenerating ? 'Synthesizing...' : 'Generate & Share'}
                   </button>
                </div>
             </div>

             <div className="flex items-center gap-4 p-4 bg-slate-50 rounded-2xl border border-slate-100">
                <ShieldCheck className="w-5 h-5 text-emerald-500" />
                <p className="text-[9px] font-bold text-slate-400 leading-relaxed uppercase tracking-widest">CalGemini reports are encrypted and include verified somatic markers for professional metabolic tracking.</p>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};
